<?php


namespace Kodilab\LaravelBatuta\Tests\Unit\Commands;


use Illuminate\Filesystem\Filesystem;
use Kodilab\LaravelBatuta\Tests\TestCase;

class ConfigTest extends TestCase
{
    /** @var Filesystem */
    protected $filesystem;

    /** @var string */
    protected $published_path;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->removePublishedConfiguration();

        $this->filesystem = new Filesystem();
        $this->published_path = config_path('batuta.php');
    }

    protected function tearDown(): void
    {
        $this->removePublishedConfiguration();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_config_should_publish_config_files()
    {
        $this->assertFalse($this->filesystem->exists($this->published_path));

        $this->artisan('batuta:config')->run();

        $this->assertTrue($this->filesystem->exists($this->published_path));
    }

    public function test_config_with_force_option_should_overwrite_the_config_file()
    {
        $this->artisan('batuta:config')->run();
        $this->assertTrue($this->filesystem->exists($this->published_path));

        file_put_contents($this->published_path, '');
        $this->assertEquals('', file_get_contents($this->published_path));

        $this->artisan('batuta:config --force')->run();
        $this->assertNotEquals('', file_get_contents($this->published_path));
    }

    private function removePublishedConfiguration()
    {
        $this->filesystem->delete($this->published_path);
    }
}