<?php


namespace Kodilab\LaravelBatuta\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;
use Kodilab\LaravelBatuta\Contracts\Permissionable;
use Kodilab\LaravelBatuta\Exceptions\DefaultRoleNotFound;
use Kodilab\LaravelBatuta\Traits\HasPermissions;

class Role extends Model implements Permissionable
{
    use HasPermissions;

    protected $fillable = ['name', 'granted', 'default'];

    protected $casts = [
        'granted' => 'boolean',
        'default' => 'boolean'
    ];

    public function __construct(array $attributes = [])
    {
        $this->table = config('batuta.tables.roles', 'roles');

        parent::__construct($attributes);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function (Role $role) {

            if ($role->isDefault()) {
                throw new \InvalidArgumentException('Default role can not be removed');
            }

        });
    }

    public function getPermissionsTable()
    {
        return config('batuta.tables.role_permissions', 'role_permissions');
    }

    public function isDefault()
    {
        return $this->default;
    }

    public static function getDefault()
    {
        if (is_null($default = Role::where('default', true)->get()->first())) {
            throw new DefaultRoleNotFound();
        }

        return $default;
    }
}